M48
; DRILL file {KiCad 7.0.7} date 2023 October 31, Tuesday 22:22:23
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-31T22:22:23-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.575Y-4.23
T2
X3.155Y-1.865
X3.155Y-4.68
X6.6983Y-1.865
X6.6983Y-4.68
T0
M30
